/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package thfinal;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author jiang
 */
public class LietKe_JFrame extends javax.swing.JFrame {

    /**
     * Creates new form ThemNhanVien_JFrame
     */
    public LietKe_JFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        maNhanVien_jLabel = new javax.swing.JLabel();
        soHoaDon_jLabel = new javax.swing.JLabel();
        soHoaDon_jTextField = new javax.swing.JTextField();
        ngayLap_jLabel = new javax.swing.JLabel();
        ngayLap_jTextField = new javax.swing.JTextField();
        triGia_jLabel = new javax.swing.JLabel();
        triGia_jTextField = new javax.swing.JTextField();
        deleteBt = new javax.swing.JButton();
        maKH_jLabel = new javax.swing.JLabel();
        maKH_jTextField = new javax.swing.JTextField();
        maNV_jTextField = new javax.swing.JTextField();
        updateBt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        getContentPane().setLayout(layout);

        maNhanVien_jLabel.setText("Mã nhân viên");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 20;
        getContentPane().add(maNhanVien_jLabel, gridBagConstraints);

        soHoaDon_jLabel.setText("Số hóa đơn");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 24;
        getContentPane().add(soHoaDon_jLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 24;
        gridBagConstraints.gridwidth = 23;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(soHoaDon_jTextField, gridBagConstraints);

        ngayLap_jLabel.setText("Ngày lập");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 28;
        getContentPane().add(ngayLap_jLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 28;
        gridBagConstraints.gridwidth = 23;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(ngayLap_jTextField, gridBagConstraints);

        triGia_jLabel.setText("Trị giá");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 32;
        getContentPane().add(triGia_jLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 32;
        gridBagConstraints.gridwidth = 23;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(triGia_jTextField, gridBagConstraints);

        deleteBt.setText("Delete");
        deleteBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 24;
        gridBagConstraints.gridy = 36;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(deleteBt, gridBagConstraints);

        maKH_jLabel.setText("Mã khách hàng");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(maKH_jLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 23;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(maKH_jTextField, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.gridwidth = 23;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(maNV_jTextField, gridBagConstraints);

        updateBt.setText("Update");
        updateBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 36;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(updateBt, gridBagConstraints);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "SoHD", "Ma khach hang", "Ma nhan vien", "Ngay lap", "Tri gia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 29;
        gridBagConstraints.gridheight = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jScrollPane1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    
    private void deleteBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        String soHDtb = model.getValueAt(jTable1.getSelectedRow(), 0).toString();
        model.removeRow(jTable1.getSelectedRow());
        ExcuteSQLStatement.ExcuteSQLUpdate("delete from HOADON where SOHD = '" + soHDtb +"'");
    }//GEN-LAST:event_deleteBtActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        String soHDtb = model.getValueAt(jTable1.getSelectedRow(), 0).toString();
        String ngayLaptb = model.getValueAt(jTable1.getSelectedRow(), 3).toString();
        String maKHtb = model.getValueAt(jTable1.getSelectedRow(), 1).toString();
        String maNVtb = model.getValueAt(jTable1.getSelectedRow(), 2).toString();
        String triGiatb = model.getValueAt(jTable1.getSelectedRow(), 4).toString();
        maKH_jTextField.setText(maKHtb);
        maNV_jTextField.setText(maNVtb);
        soHoaDon_jTextField.setText(soHDtb);
        ngayLap_jTextField.setText(ngayLaptb);
        triGia_jTextField.setText(triGiatb);
    }//GEN-LAST:event_jTable1MouseClicked

    private void updateBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setValueAt(maKH_jTextField.getText(), jTable1.getSelectedRow(), 0);
        model.setValueAt(maNV_jTextField.getText(),jTable1.getSelectedRow(),1);
        model.setValueAt(soHoaDon_jTextField.getText(),jTable1.getSelectedRow(), 2);
        model.setValueAt(ngayLap_jTextField.getText(),jTable1.getSelectedRow(), 3);
        model.setValueAt(triGia_jTextField.getText(),jTable1.getSelectedRow(), 4);
//      ExcuteSQLStatement.ExcuteSQLUpdate("update HOADON set MAKH = '" + maKH_jTextField.getText() + "' where SOHD ='" + soHoaDon_jTextField.getText() + "'");
//      ExcuteSQLStatement.ExcuteSQLUpdate("update HOADON set MANV = '" + maNV_jTextField.getText() + "' where SOHD ='" + soHoaDon_jTextField.getText() + "'");
//      ExcuteSQLStatement.ExcuteSQLUpdate("update HOADON set NGAYLAP = '" + ngayLap_jTextField.getText() + "' where SOHD ='" + soHoaDon_jTextField.getText() + "'");
//      ExcuteSQLStatement.ExcuteSQLUpdate("update HOADON set TRIGIA = '" + triGia_jTextField.getText() + "' where SOHD ='" + soHoaDon_jTextField.getText() + "'");
//      
    }//GEN-LAST:event_updateBtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LietKe_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LietKe_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LietKe_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LietKe_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LietKe_JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteBt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel maKH_jLabel;
    private javax.swing.JTextField maKH_jTextField;
    private javax.swing.JTextField maNV_jTextField;
    private javax.swing.JLabel maNhanVien_jLabel;
    private javax.swing.JLabel ngayLap_jLabel;
    private javax.swing.JTextField ngayLap_jTextField;
    private javax.swing.JLabel soHoaDon_jLabel;
    private javax.swing.JTextField soHoaDon_jTextField;
    private javax.swing.JLabel triGia_jLabel;
    private javax.swing.JTextField triGia_jTextField;
    private javax.swing.JButton updateBt;
    // End of variables declaration//GEN-END:variables
}
