/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package thfinal;

/**
 *
 * @author jiang
 */
public class ThemNhanVien_JFrame extends javax.swing.JFrame {

    /**
     * Creates new form ThemNhanVien_JFrame
     */
    public ThemNhanVien_JFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        maNhanVien_jLabel = new javax.swing.JLabel();
        maNhanVien_jTextField = new javax.swing.JTextField();
        tenNV_jLabel = new javax.swing.JLabel();
        tenNV_jTextField = new javax.swing.JTextField();
        ngayVaoLam_jLabel = new javax.swing.JLabel();
        ngayVaoLam_jTextField = new javax.swing.JTextField();
        SDT_jLabel = new javax.swing.JLabel();
        SDT_jTextField = new javax.swing.JTextField();
        themNV_jButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        getContentPane().setLayout(layout);

        maNhanVien_jLabel.setText("Mã nhân viên");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        getContentPane().add(maNhanVien_jLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 23;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(maNhanVien_jTextField, gridBagConstraints);

        tenNV_jLabel.setText("Tên nhân viên");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        getContentPane().add(tenNV_jLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 23;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(tenNV_jTextField, gridBagConstraints);

        ngayVaoLam_jLabel.setText("Ngày vào làm");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        getContentPane().add(ngayVaoLam_jLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 23;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(ngayVaoLam_jTextField, gridBagConstraints);

        SDT_jLabel.setText("Số điện thoại");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        getContentPane().add(SDT_jLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 23;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(SDT_jTextField, gridBagConstraints);

        themNV_jButton.setText("Thêm");
        themNV_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themNV_jButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 20;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(themNV_jButton, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void themNV_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themNV_jButtonActionPerformed
        // TODO add your handling code here:
        String maNV = maNhanVien_jTextField.getText();
        String tenNV = tenNV_jTextField.getText();
        String ngayVaoLam = ngayVaoLam_jTextField.getText();
        String SDT = SDT_jTextField.getText(); 
        ExcuteSQLStatement.ExcuteSQLUpdate("insert into NHANVIEN values ('" + maNV + "', '" +tenNV +"','" +ngayVaoLam+ "','" +SDT +"')");
        maNhanVien_jTextField.setText("");
        tenNV_jTextField.setText("");
        ngayVaoLam_jTextField.setText("");
        SDT_jTextField.setText("");
        System.out.println("Da them NV thanh cong!");
    }//GEN-LAST:event_themNV_jButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemNhanVien_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemNhanVien_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemNhanVien_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemNhanVien_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemNhanVien_JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SDT_jLabel;
    private javax.swing.JTextField SDT_jTextField;
    private javax.swing.JLabel maNhanVien_jLabel;
    private javax.swing.JTextField maNhanVien_jTextField;
    private javax.swing.JLabel ngayVaoLam_jLabel;
    private javax.swing.JTextField ngayVaoLam_jTextField;
    private javax.swing.JLabel tenNV_jLabel;
    private javax.swing.JTextField tenNV_jTextField;
    private javax.swing.JButton themNV_jButton;
    // End of variables declaration//GEN-END:variables
}
